school: VARCHAR(10)
sex: VARCHAR(1)
age: INTEGER
address: VARCHAR(100)
famsize: VARCHAR(10)
pstatus: VARCHAR(10)
medu: INTEGER
fedu: INTEGER
mjob: VARCHAR(50)
fjob: VARCHAR(50)
reason: VARCHAR(50)
guardian: VARCHAR(50)
traveltime: INTEGER
studytime: INTEGER
failures: INTEGER
schoolsup: VARCHAR(10)
famsup: VARCHAR(10)
paid: VARCHAR(10)
activities: VARCHAR(20)
nursery: VARCHAR(10)
higher: VARCHAR(10)
internet: VARCHAR(10)
romantic: VARCHAR(10)
famrel: INTEGER
freetime: INTEGER
goout: INTEGER
dalc: INTEGER
walc: INTEGER
health: INTEGER
absences: INTEGER
g1: INTEGER
g2: INTEGER
g3: INTEGER
id : INTEGER
creating_timestamp: DATETIME